[plugins]
krew = "https://github.com/soupglasses/mise-krew"

[tools]
awscli = { version = "latest", symlink_bins = "true" }
cargo-binstall = "latest"
go = "1.26"
kubectl = "latest"
rust = "latest"
just = "latest"
gcloud = "latest"
"krew:tree" = "latest"
