[plugins]
krew = "https://github.com/soupglasses/mise-krew"

[tools]
awscli = { version = "latest", symlink_bins = "true" }
cargo-binstall = "latest"
go = "1.26"
kubectl = "latest"
rust = "latest"
just = "latest"
gcloud = "latest"
"krew:tree" = "latest"
"krew:ctx" = "latest"
"krew:curl" = "latest"
"krew:ns" = "latest"
"krew:get-all" = "latest"
"krew:stern" = "latest"
"krew:node-shell" = "latest"
"krew:lineage" = "latest"
"krew:sniff" = "latest"
"krew:deprecations" = "latest"
"krew:rolesum" = "latest"
"krew:rbac-tool" = "latest"
"krew:gadget" = "latest"
git-lfs = "latest"
terraform = "latest"
terragrunt = "latest"
dagger = "latest"
fzf = "latest"
"krew:modify-secret" = "latest"
"krew:ktop" = "latest"
helm = "latest"
npm = "latest"
node = "latest"
java = "temurin-21"
k9s = "latest"
opentofu = "latest"
jq = "latest"
worktrunk = "latest"
gh = "latest"
claude-code = "latest"
